version: "3"

x-aws-vpc: "vpc-6214d91f"

services:
  blog-backend:
    container_name: blog-backend
    env_file: .env
    build:
      context: .
      dockerfile: ./apps/blog-backend/Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        PUBLIC_API_URL: ${PUBLIC_API_URL}
    restart: always
    ports:
      - 8080:8080

  astro-blog:
    container_name: astro-blog
    env_file: .env
    build:
      context: .
      dockerfile: ./apps/astro-blog/Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        PUBLIC_API_URL: ${PUBLIC_API_URL}
    restart: always
    ports:
      - 4321:4321
