services:
  blog-backend:
    image: ${DOCKER_REGISTRY}/blog-backend
    container_name: blog-backend
    env_file: .env.prod
    build:
      context: .
      dockerfile: ./apps/blog-backend/Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        PUBLIC_FRONTEND_URL: ${PUBLIC_FRONTEND_URL}
    restart: always
    ports:
      - 8080:8080
    networks:
      - blog-network

  astro-blog:
    image: ${DOCKER_REGISTRY}/astro-blog
    container_name: astro-blog
    env_file: .env.prod
    build:
      context: .
      dockerfile: ./apps/astro-blog/Dockerfile
      args:
        PUBLIC_BACKEND_API_URL: ${PUBLIC_BACKEND_API_URL}
        PUBLIC_IN_NETWORK_BACKEND_API_URL: ${PUBLIC_IN_NETWORK_BACKEND_API_URL}
        DATABASE_URL: ${DATABASE_URL}
        SUPABASE_URL: ${SUPABASE_URL}
        SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
    restart: always
    ports:
      - 80:4321 # Configure standard Http port
      - 443:4321 # Configure standard Https port
      - 4321:4321
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
