x-aws-vpc: "vpc-6214d91f"

services:
  # blog-backend has been deprecated as I don't wan't to setup proper https
  # blog-backend:
  #   image: ${DOCKER_REGISTRY}/blog-backend
  #   container_name: blog-backend
  #   env_file: .env
  #   build:
  #     context: .
  #     dockerfile: ./apps/blog-backend/Dockerfile
  #     args:
  #       DATABASE_URL: ${DATABASE_URL}
  #   restart: always
  #   ports:
  #     - 8080:8080

  astro-blog:
    image: ${DOCKER_REGISTRY}/astro-blog
    container_name: astro-blog
    env_file: .env
    build:
      context: .
      dockerfile: ./apps/astro-blog/Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        SUPABASE_URL: ${SUPABASE_URL}
        SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
    restart: always
    ports:
      - 4321:4321
