export const BUTTON_NAME = {
  astro: "astro",

  linkedin: "linkedin",
  twitter: "twitter",
  github: "github",

  // COOL LINK button names
  falsehoods_programmers: "falsehoods_programmers",
  best_gcp_region: "best_gcp_region",
  how_to_write_blog: "how_to_write_blog",
  styled_components_alternative: "styled_components_alternative",
  callback_refs: "callback_refs",
  meta_interview_tips: "meta_interview_tips",
  no_need_use_effect: "no_need_use_effect",
  link_opening_guidelines: "link_opening_guidelines",
  css_styling_ssr_age: "css_styling_ssr_age",
  stylex_alternative: "stylex_alternative",
  docker_compose_production: "docker_compose_production",
  problems_solved_languages: "problems_solved_languages",
  two_reacts_article: "two_reacts_article",
  rsc_video: "rsc_video",
  choose_boring_technology: "choose_boring_technology",
  animated_icons: "animated_icons",
  rsc_good_bad_ugly: "rsc_good_bad_ugly",
  background_grid_creator: "background_grid_creator",
  css_layout_modes: "css_layout_modes",
  javascript_seo: "javascript_seo",
  human_problems_software: "human_problems_software",
  handle_favicons: "handle_favicons",
  css_color_handling: "css_color_handling",
  twitter_type_methods: "twitter_type_methods",
  ask_full_question: "ask_full_question",
  image_to_svg: "image_to_svg",
  dont_use_handle_click: "dont_use_handle_click",
  typeface_vs_font: "typeface_vs_font",
  handle_svg_react: "handle_svg_react",
  why_not_styled_components: "why_not_styled_components",
  google_maps_with_sql: "google_maps_with_sql",
  track_web_performance: "track_web_performance",
  strict_type_inputs: "strict_type_inputs",
  type_safe_url_routes: "type_safe_url_routes",
  more_css_some_react: "more_css_some_react",
  general_react_opinions: "general_react_opinions",
  react_query_main_blog: "react_query_main_blog",
  react_query_creator_site: "react_query_creator_site",
  redux_creator_blog: "redux_creator_blog",
  margin_is_bad: "margin_is_bad",
  docs_use_effect: "docs_use_effect",
  js_talks_2023: "js_talks_2023",
  slow_types_intro_mysql: "slow_types_intro_mysql",
  consistent_typography: "consistent_typography",
  demystifying_inp: "demystifying_inp",
  visualization_primitives: "visualization_primitives",
  modern_cms: "modern_cms",
  shipping_big_companies: "shipping_big_companies",
  github_codeowners_docs: "github_codeowners_docs",
  sticky_element_pinning: "sticky_element_pinning",
  give_away_legos: "give_away_legos",
  smallest_files: "smallest_files",
  open_source_icons: "open_source_icons",
  nextjs_production_example: "nextjs_production_example",
  fake_data_creation: "fake_data_creation",
  shorthand_syntax_harmful: "shorthand_syntax_harmful",
  best_icon_library: "best_icon_library",
  force_popup: "force_popup",
  use_deferred_value: "use_deferred_value",
  do_you_need_graphql: "do_you_need_graphql",
  metatags_generator: "metatags_generator",
  generate_favicons: "generate_favicons",
  pass_components_as_props: "pass_components_as_props",
  frontend_guidelines: "frontend_guidelines",
  css_beginner_summary: "css_beginner_summary",
  is_it_worth_optimizing_workflow: "is_it_worth_optimizing_workflow",
} as const

export type ButtonName = keyof typeof BUTTON_NAME
